import org.gradle.internal.os.OperatingSystem

pluginManagement {
    repositories {
        String wpilibYear = '2027_alpha5'
        File wpilibHome
        if (OperatingSystem.current().isWindows()) {
            String publicFolder = System.getenv('PUBLIC')
            if (publicFolder == null) {
                publicFolder = 'C:\\Users\\Public'
            }
            wpilibHome = new File(new File(publicFolder, 'wpilib'), wpilibYear)
        } else {
            wpilibHome = new File(new File(System.getProperty('user.home'), 'wpilib'), wpilibYear)
        }
        maven {
            name = 'wpilibHome'
            url = new File(wpilibHome, 'maven')
        }
        mavenLocal()
        gradlePluginPortal()
    }
}

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.10.0'
}

Properties props = System.getProperties()
props.setProperty("org.gradle.internal.native.headers.unresolved.dependencies.ignore", "true")

rootProject.name = 'autopilot'
include('lib')
