/*
 * This source file was generated by the Gradle 'init' task
 */
package com.therekrab.autopilot;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AutopilotTest {
}
