/*
 * This source file was generated by the Gradle 'init' task
 */
package com.therekrab.autopilot;

import edu.wpi.first.math.geometry.Rotation2d;

public class Autopilot {
  public boolean someLibraryMethod() {
    Rotation2d rot = Rotation2d.kZero;
    return rot.getSin() == 0;
  }
}
